spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/marketPlaceDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
